/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarIndexRouteImport } from './routes/criar.index'
import { Route as CriarCategoryRouteImport } from './routes/criar.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarIndexRoute = CriarIndexRouteImport.update({
  id: '/criar/',
  path: '/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarCategoryRoute = CriarCategoryRouteImport.update({
  id: '/criar/$category',
  path: '/criar/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/criar': typeof CriarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar/$category' | '/criar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar/$category' | '/criar'
  id: '__root__' | '/' | '/criar/$category' | '/criar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarCategoryRoute: typeof CriarCategoryRoute
  CriarIndexRoute: typeof CriarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/': {
      id: '/criar/'
      path: '/criar'
      fullPath: '/criar/'
      preLoaderRoute: typeof CriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/$category': {
      id: '/criar/$category'
      path: '/criar/$category'
      fullPath: '/criar/$category'
      preLoaderRoute: typeof CriarCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarCategoryRoute: CriarCategoryRoute,
  CriarIndexRoute: CriarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
