/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarIndexRouteImport } from './routes/criar.index'
import { Route as ParaSlugRouteImport } from './routes/para.$slug'
import { Route as CriarCategoryRouteImport } from './routes/criar.$category'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarIndexRoute = CriarIndexRouteImport.update({
  id: '/criar/',
  path: '/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaSlugRoute = ParaSlugRouteImport.update({
  id: '/para/$slug',
  path: '/para/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarCategoryRoute = CriarCategoryRouteImport.update({
  id: '/criar/$category',
  path: '/criar/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/para/$slug': typeof ParaSlugRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/para/$slug': typeof ParaSlugRoute
  '/criar': typeof CriarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/criar/$category': typeof CriarCategoryRoute
  '/para/$slug': typeof ParaSlugRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/entrar'
    | '/checkout/return'
    | '/criar/$category'
    | '/para/$slug'
    | '/criar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/entrar'
    | '/checkout/return'
    | '/criar/$category'
    | '/para/$slug'
    | '/criar'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/entrar'
    | '/checkout/return'
    | '/criar/$category'
    | '/para/$slug'
    | '/criar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  CriarCategoryRoute: typeof CriarCategoryRoute
  ParaSlugRoute: typeof ParaSlugRoute
  CriarIndexRoute: typeof CriarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/': {
      id: '/criar/'
      path: '/criar'
      fullPath: '/criar/'
      preLoaderRoute: typeof CriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/$slug': {
      id: '/para/$slug'
      path: '/para/$slug'
      fullPath: '/para/$slug'
      preLoaderRoute: typeof ParaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/$category': {
      id: '/criar/$category'
      path: '/criar/$category'
      fullPath: '/criar/$category'
      preLoaderRoute: typeof CriarCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  EntrarRoute: EntrarRoute,
  CriarCategoryRoute: CriarCategoryRoute,
  ParaSlugRoute: ParaSlugRoute,
  CriarIndexRoute: CriarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
